curl 'https://steamcommunity.com/id/iamjoric/myworkshopfiles/?browsesort=myplayedfiles&browsefilter=myplayedfiles&p=1' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: max-age=0' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Referer: https://steamcommunity.com/id/iamjoric/myworkshopfiles/' \
  -H 'Accept-Language: en-US,en;q=0.9,ru;q=0.8,ja;q=0.7' \
  --compressed -s | sed -ne 's/^.*Showing 1-10 of \(.*\) entries.*$/\1/p'
